#!/bin/bash

send_message () { curl -i - H "Accept: application/json" -X POST -H "Content-Type: application/json" -data :"{ \"content\": ${1} }" "${WEBHOOK_URL}" ; }
get_git_update () {
    cd "${1}" || exit
    UPDATED_BRANCHES=$(git fetch --all | grep -o "origin/\S\+")
        for BRANCH in ${UPDATED_BRANCHES}
        do
            git checkout "${BRANCH}" --quiet
            echo "On branch ${BRANCH}:"
            git log --pretty=format:"%h%x09%an%x09%ad%x09%s" origin/master.. && \
            git pull --all --quiet
            echo ""
            git checkout master --quiet
        done; cd ..
    }

echo "FETCHING DATA FOR ${*} -- $(date)"
cd /home/"${USER}"/directories || exit
for DIR_PATH in "${@}"
do
    echo "Fetching data for ${DIR_PATH}..."
    FETCH_RESULT=$(get_git_update "${DIR_PATH}") 2>&1
    if [ "${FETCH_RESULT}" != "" ]; then
        send_message "New commits for ${DIR_PATH}:"
        send_message "${FETCH_RESULT}"
    else echo "Nothing has been sent!"
    fi
done
